/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookingsInternal;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class ManageBookings extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageBookings
     */
    public ManageBookings() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        displayData();
        
    TableColumnModel columnModel = bookingsTable.getColumnModel();
       
        columnModel.getColumn(0).setHeaderValue("ID");
        columnModel.getColumn(1).setHeaderValue("ROOM TYPE");
        columnModel.getColumn(2).setHeaderValue("FIRSTNAME");
        columnModel.getColumn(3).setHeaderValue("LASTNAME");
        columnModel.getColumn(4).setHeaderValue("EMAIL");
        columnModel.getColumn(5).setHeaderValue("CHECK-IN");
        columnModel.getColumn(6).setHeaderValue("CHECK-OUT");
        columnModel.getColumn(7).setHeaderValue("TIME-IN");
        columnModel.getColumn(8).setHeaderValue("STATUS");

    bookingsTable.getTableHeader().repaint();
    
    }
    
    public void displayData() {
    try {
        dbConnector dbc = new dbConnector();
        String query = "SELECT b.b_id, r.r_type, "
                     + "b.g_fname, b.g_lname, b.g_email, "
                     + "b.b_cin, b.b_cout, b.time_in, b.b_status "
                     + "FROM tbl_bookings b "
                     + "JOIN tbl_room r ON b.rm_id = r.room_id";

        ResultSet rs = dbc.getData(query);
        bookingsTable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingsTable = new javax.swing.JTable();

        bookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(bookingsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
