/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SelectToPrint;

import Admin.AdminPage;
import Admin.GuestPrinting;
import Admin.UserPrinting;
import MainPage.LoginPage;
import User.UserPage;
import UsersInternal.AddUserForm;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class ManagePrints extends javax.swing.JFrame {

    /**
     * Creates new form ManagePrints
     */
    public ManagePrints() {
        initComponents();
        
        displayData();
    }
    
     Color hovercolor = new Color(255,255,255);
     Color exitcolor = new Color(0,0,153);
     Color foregroundcolor = new Color(0,0,0);
     Color exitforegroundcolor = new Color(255,255,255);
    
    public void displayData(){ 
    try {
        dbConnector dbc = new dbConnector();
        ResultSet rs1 = dbc.getData("SELECT u_id, u_fname, u_usern, u_status FROM tbl_user WHERE u_status = 'Active'");
        usersTable.setModel(DbUtils.resultSetToTableModel(rs1));
        rs1.close();

        ResultSet rs2 = dbc.getData("SELECT b_id, g_fname, g_lname, b_status FROM tbl_bookings WHERE b_status = 'Approved'");
        guestsTable.setModel(DbUtils.resultSetToTableModel(rs2));
        rs2.close();

    } catch(SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guestsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        print_button = new javax.swing.JLabel();
        b_button = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guestsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(guestsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 390, 280));

        usersTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(usersTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 390, 280));

        print_button.setBackground(new java.awt.Color(0, 0, 153));
        print_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        print_button.setForeground(new java.awt.Color(255, 255, 255));
        print_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print_button.setText("Print");
        print_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        print_button.setOpaque(true);
        print_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_buttonMouseExited(evt);
            }
        });
        jPanel1.add(print_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 150, 40));

        b_button.setBackground(new java.awt.Color(0, 0, 153));
        b_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_button.setForeground(new java.awt.Color(255, 255, 255));
        b_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_button.setText("Back");
        b_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_button.setOpaque(true);
        b_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_buttonMouseExited(evt);
            }
        });
        jPanel1.add(b_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 150, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRINT");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 230, 40);

        minimize1.setBackground(new java.awt.Color(0, 0, 153));
        minimize1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        minimize1.setForeground(new java.awt.Color(255, 255, 255));
        minimize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize1.setText("—");
        minimize1.setOpaque(true);
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize1MouseExited(evt);
            }
        });
        jPanel3.add(minimize1);
        minimize1.setBounds(810, 10, 40, 30);

        exit1.setBackground(new java.awt.Color(0, 0, 153));
        exit1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("X");
        exit1.setOpaque(true);
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        jPanel3.add(exit1);
        exit1.setBounds(850, 10, 40, 30);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GUEST");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 390, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 390, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void print_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseClicked
    int userRow = usersTable.getSelectedRow();
    int guestRow = guestsTable.getSelectedRow();

    dbConnector dbc = new dbConnector();

    if (userRow != -1) {
        int selectedUserId = Integer.parseInt(usersTable.getValueAt(userRow, 0).toString());

        try {
            ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '" + selectedUserId + "'");
            if (rs.next()) {

                UserPrinting up = new UserPrinting();

                up.id.setText("" + rs.getInt("u_id"));
                up.fn.setText(rs.getString("u_fname"));
                up.ln.setText(rs.getString("u_lname"));
                up.at.setText(rs.getString("u_type"));
                up.em.setText(rs.getString("u_email"));
                up.cn.setText(rs.getString("u_cnum"));
                up.un.setText(rs.getString("u_usern"));
                up.gd.setText(rs.getString("u_gen"));
                up.ag.setText("" + rs.getInt("u_age"));
                up.st.setText(rs.getString("u_status"));

                String imagePath = rs.getString("u_image");
                if (imagePath != null && !imagePath.isEmpty()) {
                    File file = new File(imagePath);
                    if (file.exists()) {
                        AddUserForm auf = new AddUserForm(); 
                        up.profile.setIcon(auf.ResizeImage(imagePath, null, up.profile));
                        up.profile.setText("");
                    } else {
                        up.profile.setText("NO PROFILE");
                        up.profile.setIcon(null);
                    }
                } else {
                    up.profile.setText("NO PROFILE");
                    up.profile.setIcon(null);
                }

                up.setVisible(true);
                this.dispose();
                
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching user data.");
        }

    } else if (guestRow != -1) {
        int selectedBookingId = Integer.parseInt(guestsTable.getValueAt(guestRow, 0).toString());

        try {
            ResultSet rs = dbc.getData("SELECT * FROM tbl_bookings WHERE b_id = '" + selectedBookingId + "'");
            if (rs.next()) {

                GuestPrinting gp = new GuestPrinting(); 

                gp.fn.setText(rs.getString("g_fname"));
                gp.ln.setText(rs.getString("g_lname"));
                gp.rid.setText("" + rs.getInt("rm_id"));
                gp.rt.setText(rs.getString("rm_type"));
                gp.ag.setText("" + rs.getInt("g_age"));
                gp.em.setText(rs.getString("g_email"));
                gp.cin.setText(rs.getString("b_cin"));
                gp.cout.setText(rs.getString("b_cout"));
                gp.cs.setText("" + rs.getDouble("b_cash"));
                gp.cng.setText("" + rs.getDouble("b_change"));

                String imagePath = rs.getString("g_image");
                if (imagePath != null && !imagePath.isEmpty()) {
                    File file = new File(imagePath);
                    if (file.exists()) {
                        AddUserForm auf = new AddUserForm();
                        gp.profile.setIcon(auf.ResizeImage(imagePath, null, gp.profile));
                        gp.profile.setText("");
                    } else {
                        gp.profile.setText("NO PROFILE");
                        gp.profile.setIcon(null);
                    }
                } else {
                    gp.profile.setText("NO PROFILE");
                    gp.profile.setIcon(null);
                }

                gp.setVisible(true);
                this.dispose();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching booking data.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a user or guest row to print.");
    }
    }//GEN-LAST:event_print_buttonMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
      
      if(sess.getUid() == 0){
      JOptionPane.showMessageDialog(null, "No Shortcut Allowed!, Login First!");
        LoginPage mpg = new LoginPage();
        mpg.setVisible(true);
        this.dispose();
      }else{
       
      }
    }//GEN-LAST:event_formWindowActivated

    private void b_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseClicked
        Session sess = Session.getInstance();
    String type = sess.getType();

    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    this.dispose();
    }//GEN-LAST:event_b_buttonMouseClicked

    private void b_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseEntered
        b_button.setBackground(hovercolor);
        b_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_b_buttonMouseEntered

    private void b_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseExited
        b_button.setBackground(exitcolor);
        b_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_b_buttonMouseExited

    private void print_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseEntered
        print_button.setBackground(hovercolor);
        print_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_print_buttonMouseEntered

    private void print_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseExited
        print_button.setBackground(exitcolor);
        print_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_print_buttonMouseExited

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimize1MouseClicked

    private void minimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseEntered
        minimize1.setBackground(new java.awt.Color(240,240,240));
        minimize1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_minimize1MouseEntered

    private void minimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseExited
        minimize1.setBackground(new java.awt.Color(0,0,153));
        minimize1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_minimize1MouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        
    dbConnector dbc = new dbConnector();
    Session sess = Session.getInstance();
    
    String action = "Logged Out from the System";
    dbc.insertData("INSERT INTO tbl_logs (usr_id, l_actions, l_date) VALUES ('"+sess.getUid()+"', '"+action+"', '"+LocalDateTime.now()+"' ) ");
        
        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
        exit1.setBackground(new java.awt.Color(240,240,240));
        exit1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
        exit1.setBackground(new java.awt.Color(0,0,153));
        exit1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exit1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePrints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePrints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePrints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePrints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePrints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_button;
    private javax.swing.JLabel exit1;
    public javax.swing.JTable guestsTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minimize1;
    private javax.swing.JLabel print_button;
    public javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
