/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomsInternal;

import Admin.AdminPage;
import User.UserPage;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.Window;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class AddRoomForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddRoomForm
     */
    public AddRoomForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    displayData();
     updateRoomPrice();
     
     Border line = BorderFactory.createLineBorder(Color.BLACK);
        Border margin = BorderFactory.createEmptyBorder(5, 10, 5, 10);
        Border compound = BorderFactory.createCompoundBorder(line, margin);

    r_type.setBorder(compound);
    r_price.setBorder(compound);

        r_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomPrice();
            }
        });
    
    }
    
     Color hovercolor = new Color(255,255,255);
     Color exitcolor = new Color(0,0,153);
     Color foregroundcolor = new Color(0,0,0);
     Color exitforegroundcolor = new Color(255,255,255);
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT room_id, r_type, r_price, r_status FROM tbl_room");
            arTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
     private void updateRoomPrice() {
        String selectedRoomType = (String) r_type.getSelectedItem();
        String priceText = "";

        switch (selectedRoomType) {
            case "Standard Room":
                priceText = "500 Pesos";
                break;
            case "Deluxe Room":
                priceText = "750 Pesos";
                break;
            case "Suite Room":
                priceText = "1000 Pesos";
                break;
            default:
                priceText = "Unknown";
        }

        r_price.setText(priceText);
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r_type = new javax.swing.JComboBox<>();
        r_price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        add_button = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        arTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(arTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 360, 280);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VIEW ROOMS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 20, 150, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(470, 20, 380, 350);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ROOM TYPE:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(50, 90, 80, 17);

        r_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Room", "Deluxe Room", "Suite Room" }));
        jPanel3.add(r_type);
        r_type.setBounds(160, 80, 150, 40);

        r_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r_price.setEnabled(false);
        r_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_priceActionPerformed(evt);
            }
        });
        jPanel3.add(r_price);
        r_price.setBounds(160, 170, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ROOM PRICE:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 180, 86, 20);

        add_button.setBackground(new java.awt.Color(0, 0, 153));
        add_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_button.setText("ADD");
        add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_button.setOpaque(true);
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_buttonMouseExited(evt);
            }
        });
        jPanel3.add(add_button);
        add_button.setBounds(160, 260, 150, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 20, 410, 350);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_priceActionPerformed

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
          dbConnector dbc = new dbConnector();

    String selectedRoomType = (String) r_type.getSelectedItem();
    String price = "";

    switch (selectedRoomType) {
        case "Standard Room":
            price = "500";
            break;
        case "Deluxe Room":
            price = "750";
            break;
        case "Suite Room":
            price = "1000";
            break;
        default:
            JOptionPane.showMessageDialog(null, "Invalid room type selected.");
            return;
    }
    
    if (dbc.insertData("INSERT INTO tbl_room (r_type, r_price, r_status) "
            + "VALUES ('" + selectedRoomType + "', '" + price + "', 'Vacant')")) {

        JOptionPane.showMessageDialog(null, "Room added successfully!");
        
    Session sess = Session.getInstance();
    String type = sess.getType();

    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }        
    
    } else {
        JOptionPane.showMessageDialog(null, "Failed to add room. Please try again.");
    }
    }//GEN-LAST:event_add_buttonMouseClicked

    private void add_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseEntered
        add_button.setBackground(hovercolor);
        add_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_add_buttonMouseEntered

    private void add_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseExited
        add_button.setBackground(exitcolor);
        add_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_add_buttonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_button;
    private javax.swing.JTable arTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField r_price;
    private javax.swing.JComboBox<String> r_type;
    // End of variables declaration//GEN-END:variables
}
