/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomsInternal;

import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class ViewRoomForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewRoomForm
     */
    public ViewRoomForm() {
        initComponents();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    displayData();
      updateRoomPrice();
      
      Border line = BorderFactory.createLineBorder(Color.BLACK);
        Border margin = BorderFactory.createEmptyBorder(5, 10, 5, 10);
        Border compound = BorderFactory.createCompoundBorder(line, margin);

    r_type.setBorder(compound);
    rp.setBorder(compound);
     
     r_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomPrice();
            }
        });
     
     urTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urTableMouseClicked(evt);
            }
        });
     
     TableColumnModel columnModel = urTable.getColumnModel();
       
        columnModel.getColumn(0).setHeaderValue("ID");
        columnModel.getColumn(1).setHeaderValue("ROOM TYPE");
        columnModel.getColumn(2).setHeaderValue("ROOM PRICE");
        columnModel.getColumn(3).setHeaderValue("ROOM STATUS");

    urTable.getTableHeader().repaint();
    
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT room_id, r_type, r_price, r_status FROM tbl_room");
            urTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
    private void updateRoomPrice() {
        String selectedRoomType = (String) r_type.getSelectedItem();
        String priceText = "";

        switch (selectedRoomType) {
            case "Standard Room":
                priceText = "500 Pesos";
                break;
            case "Deluxe Room":
                priceText = "750 Pesos";
                break;
            case "Suite Room":
                priceText = "1000 Pesos";
                break;
            default:
                priceText = "Unknown";
        }

        rp.setText(priceText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        r_type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        urTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        urTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 80, 360, 280);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        r_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Room", "Deluxe Room", "Suite Room" }));
        r_type.setEnabled(false);
        jPanel2.add(r_type);
        r_type.setBounds(160, 80, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ROOM TYPE:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 90, 80, 17);

        rp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rp.setEnabled(false);
        rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpActionPerformed(evt);
            }
        });
        jPanel2.add(rp);
        rp.setBounds(160, 170, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ROOM PRICE:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 180, 86, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 410, 350);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VIEW ROOMS");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(140, 20, 150, 17);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(470, 20, 380, 350);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urTableMouseClicked
        int rowIndex = urTable.getSelectedRow();

        if (rowIndex >= 0) {
            String roomType = urTable.getValueAt(rowIndex, 1).toString();
            String roomPrice = urTable.getValueAt(rowIndex, 2).toString();

            r_type.setSelectedItem(roomType);
            rp.setText(roomPrice + " Pesos");
        }
    }//GEN-LAST:event_urTableMouseClicked

    private void rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> r_type;
    private javax.swing.JTextField rp;
    private javax.swing.JTable urTable;
    // End of variables declaration//GEN-END:variables
}
