/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import Admin.AdminPage;
import User.UserPage;
import config.HashPass;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Mark Kevin Romo
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public LoginPage() {
        initComponents();
        this.setResizable(false);
        
Border line = BorderFactory.createLineBorder(Color.BLACK);
Border margin = BorderFactory.createEmptyBorder(5, 10, 5, 10); 
Border compound = BorderFactory.createCompoundBorder(line, margin);

un.setBorder(compound);
ps.setBorder(compound);
    }
    
    static String status;
    static String type;
    
        Color hovercolor = new Color(204,204,204);
        Color exitcolor = new Color(255,255,255);
    
    public static boolean loginAcc(String username, String password){
    dbConnector connector = new dbConnector();
    
    try{
        String query = "SELECT * FROM tbl_user WHERE u_usern = '" +username+ "'";
        ResultSet resultSet = connector.getData(query);
    if(resultSet.next()){
        
    
        String hash = resultSet.getString("u_pass");
        String rehash = HashPass.hashPassword(password);
        if(hash.equals(rehash)){
        status = resultSet.getString("u_status");
        type = resultSet.getString("u_type");
        
        Session sess = Session.getInstance();
        
        sess.setUid(resultSet.getInt("u_id"));
        sess.setFname(resultSet.getString("u_fname"));
        sess.setLname(resultSet.getString("u_lname"));
        sess.setEmail(resultSet.getString("u_email"));
        sess.setCnum(resultSet.getString("u_cnum"));
        sess.setUsername(resultSet.getString("u_usern"));
        sess.setPassword(resultSet.getString("u_pass"));
        sess.setGender(resultSet.getString("u_gen"));
        sess.setAge(resultSet.getString("u_age"));
        sess.setType(resultSet.getString("u_type"));
        sess.setStatus(resultSet.getString("u_status"));
        sess.setU_image(resultSet.getString("u_image"));
         
        
    return true;
    
}else{
    return false;
}
       
}else{
    return false;
}
}catch (SQLException | NoSuchAlgorithmException  ex){
    return false;
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        l_button = new javax.swing.JLabel();
        r_button = new javax.swing.JLabel();
        s_pass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COZYSTAY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 340, 60));

        un.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 320, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome back User! Please fill the details below.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 320, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign In or Create an Account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 320, 60));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Forgot Password?");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 30));

        ps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 320, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(87, 171, 380, 150);

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel3.add(minimize);
        minimize.setBounds(470, 10, 41, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(510, 10, 40, 30);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 560, 510));

        l_button.setBackground(new java.awt.Color(255, 255, 255));
        l_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_button.setText("Login");
        l_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l_button.setOpaque(true);
        l_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_buttonMouseExited(evt);
            }
        });
        jPanel1.add(l_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 150, 40));

        r_button.setBackground(new java.awt.Color(255, 255, 255));
        r_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r_button.setText("Register");
        r_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        r_button.setOpaque(true);
        r_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                r_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                r_buttonMouseExited(evt);
            }
        });
        jPanel1.add(r_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, 40));

        s_pass.setBackground(new java.awt.Color(0, 0, 153));
        s_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s_pass.setForeground(new java.awt.Color(255, 255, 255));
        s_pass.setText("Show Password");
        s_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_passActionPerformed(evt);
            }
        });
        jPanel1.add(s_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        RecoveryPage rcp = new RecoveryPage();
        rcp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void l_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_buttonMouseClicked
if (un.getText().isEmpty() || ps.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
            return;
        }

        String password = String.valueOf(ps.getPassword());
    if (password.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long!");
            ps.setText("");
            return;
        }

    if (!loginAcc(un.getText(), password)) {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
            return;
        }

    if (!(type.equals("Admin") || type.equals("User"))) {
            JOptionPane.showMessageDialog(null, "No Account Type Found, Contact the Administrator!");
            return;
        }

    if (!status.equals("Active")) {
            JOptionPane.showMessageDialog(null, "Account is Inactive, Contact the Administrator!");
            return;
        }
    
    dbConnector dbc = new dbConnector();
    Session sess = Session.getInstance();
    String action = "Logged In from the System";
    dbc.insertData("INSERT INTO tbl_logs (usr_id, l_actions, l_date) VALUES ('"+sess.getUid()+"', '"+action+"', '"+LocalDateTime.now()+"' ) ");
    
        
        JOptionPane.showMessageDialog(null, "Login Successfully!");
        

        if (type.equals("Admin")) {
            AdminPage hmp = new AdminPage();
            hmp.setVisible(true);
        } else if (type.equals("User")) {
            UserPage usp = new UserPage();
            usp.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_l_buttonMouseClicked

    private void l_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_buttonMouseEntered
         l_button.setBackground(hovercolor);  
    }//GEN-LAST:event_l_buttonMouseEntered

    private void l_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_buttonMouseExited
         l_button.setBackground(exitcolor);  
    }//GEN-LAST:event_l_buttonMouseExited

    private void r_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_buttonMouseClicked
        RegistrationForm rfm = new RegistrationForm();
        rfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_r_buttonMouseClicked

    private void r_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_buttonMouseEntered
        r_button.setBackground(hovercolor);
    }//GEN-LAST:event_r_buttonMouseEntered

    private void r_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_buttonMouseExited
        r_button.setBackground(exitcolor);
    }//GEN-LAST:event_r_buttonMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
         setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
       minimize.setBackground(Color.white);
    }//GEN-LAST:event_minimizeMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
       exit.setBackground(new java.awt.Color(240,240,240)); 
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
       exit.setBackground(Color.white);
    }//GEN-LAST:event_exitMouseExited

    private void s_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_passActionPerformed
        if(s_pass.isSelected()){
            ps.setEchoChar((char)0);
        }  else {
            ps.setEchoChar('●');
        }
    }//GEN-LAST:event_s_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l_button;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField ps;
    private javax.swing.JLabel r_button;
    private javax.swing.JCheckBox s_pass;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
