/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Account.AccDetails;
import Account.ChangePass;
import Account.ManageLogs;
import Account.RecoverAcc;
import MainPage.LoginPage;
import User.UserPage;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Mark Kevin Romo
 */
public class AccountDetails extends javax.swing.JFrame {

    /**
     * Creates new form AccountDetails
     */
    
    private boolean canClickRecovery = true;
    
    public AccountDetails() {
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowOpened(java.awt.event.WindowEvent evt) {
        l_accdMouseClicked(null);
    }
});
        
    }
    
        Color hovercolor = new Color(255,255,255);
        Color button_hovercolor = new Color(240,240,240);
        Color exitcolor = new Color(0,0,153);
        Color foregroundcolor = new Color(0,0,0);
        Color exitforegroundcolor = new Color(255,255,255);
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        acc_uname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_accd = new javax.swing.JLabel();
        l_changep = new javax.swing.JLabel();
        l_recover = new javax.swing.JLabel();
        l_logs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(971, 426));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BACK");
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 430, 240, 60);

        acc_uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acc_uname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(acc_uname);
        acc_uname.setBounds(90, 20, 140, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 80, 70);

        l_accd.setBackground(new java.awt.Color(0, 0, 153));
        l_accd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_accd.setForeground(new java.awt.Color(255, 255, 255));
        l_accd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_accd.setText("ACCOUNT DETAILS");
        l_accd.setOpaque(true);
        l_accd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_accdMouseClicked(evt);
            }
        });
        jPanel3.add(l_accd);
        l_accd.setBounds(0, 100, 240, 60);

        l_changep.setBackground(new java.awt.Color(0, 0, 153));
        l_changep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_changep.setForeground(new java.awt.Color(255, 255, 255));
        l_changep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_changep.setText("CHANGE PASSWORD");
        l_changep.setOpaque(true);
        l_changep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_changepMouseClicked(evt);
            }
        });
        jPanel3.add(l_changep);
        l_changep.setBounds(0, 180, 240, 60);

        l_recover.setBackground(new java.awt.Color(0, 0, 153));
        l_recover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_recover.setForeground(new java.awt.Color(255, 255, 255));
        l_recover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_recover.setText("RECOVERY ");
        l_recover.setOpaque(true);
        l_recover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_recoverMouseClicked(evt);
            }
        });
        jPanel3.add(l_recover);
        l_recover.setBounds(0, 260, 240, 60);

        l_logs.setBackground(new java.awt.Color(0, 0, 153));
        l_logs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_logs.setForeground(new java.awt.Color(255, 255, 255));
        l_logs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_logs.setText("LOGS");
        l_logs.setOpaque(true);
        l_logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_logsMouseClicked(evt);
            }
        });
        jPanel3.add(l_logs);
        l_logs.setBounds(0, 340, 240, 60);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 510));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACCOUNT DASHBOARD");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(12, 26, 240, 21);

        minimize.setBackground(new java.awt.Color(0, 0, 255));
        minimize.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel4.add(minimize);
        minimize.setBounds(780, 10, 41, 30);

        exit.setBackground(new java.awt.Color(0, 0, 255));
        exit.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(820, 10, 40, 30);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 870, 60));

        DesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesktopPaneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel2.add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 870, 440));

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 870, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesktopPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DesktopPaneMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    Session sess = Session.getInstance();
    String type = sess.getType();

    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
         Session sess = Session.getInstance();

   if (sess.isHasRecoveryQuestions()) {
    l_recover.setEnabled(false);       
    l_recover.setForeground(Color.GRAY);  
    canClickRecovery = false;            
    } else {
    l_recover.setEnabled(true);
    l_recover.setForeground(Color.BLUE);
    canClickRecovery = true;
}
    }//GEN-LAST:event_formWindowActivated

    private void l_changepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_changepMouseClicked
        
        l_accd.setBackground(exitcolor);
        l_accd.setForeground(exitforegroundcolor);
        l_changep.setBackground(hovercolor);
        l_changep.setForeground(foregroundcolor);
        l_recover.setBackground(exitcolor);
        l_recover.setForeground(exitforegroundcolor);
        l_logs.setBackground(exitcolor);
        l_logs.setForeground(exitforegroundcolor);
        
        DesktopPane.removeAll();
        ChangePass cp = new ChangePass();
        DesktopPane.add(cp).setVisible(true);
    }//GEN-LAST:event_l_changepMouseClicked

    private void l_accdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_accdMouseClicked
        
        l_accd.setBackground(hovercolor);
        l_accd.setForeground(foregroundcolor);
        l_changep.setBackground(exitcolor);
        l_changep.setForeground(exitforegroundcolor);
        l_recover.setBackground(exitcolor);
        l_recover.setForeground(exitforegroundcolor);
        l_logs.setBackground(exitcolor);
        l_logs.setForeground(exitforegroundcolor);
        
        DesktopPane.removeAll();
        AccDetails acd = new AccDetails();
        DesktopPane.add(acd).setVisible(true);
    }//GEN-LAST:event_l_accdMouseClicked

    private void l_recoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_recoverMouseClicked
    
        if (!canClickRecovery) return;
        
        l_accd.setBackground(exitcolor);
        l_accd.setForeground(exitforegroundcolor);
        l_changep.setBackground(exitcolor);
        l_changep.setForeground(exitforegroundcolor);
        l_recover.setBackground(hovercolor);
        l_recover.setForeground(foregroundcolor);
        l_logs.setBackground(exitcolor);
        l_logs.setForeground(exitforegroundcolor);
          
        DesktopPane.removeAll();
        RecoverAcc ra = new RecoverAcc();
        DesktopPane.add(ra).setVisible(true);
    }//GEN-LAST:event_l_recoverMouseClicked

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseDragged

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new java.awt.Color(240,240,240));
        minimize.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(new java.awt.Color(0,0,255));
        minimize.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_minimizeMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        
    dbConnector dbc = new dbConnector();
    Session sess = Session.getInstance();
    
    String action = "Logged Out from the System";
    dbc.insertData("INSERT INTO tbl_logs (usr_id, l_actions, l_date) VALUES ('"+sess.getUid()+"', '"+action+"', '"+LocalDateTime.now()+"' ) ");
        
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(new java.awt.Color(240,240,240));
        exit.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new java.awt.Color(0,0,255));
        exit.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exitMouseExited

    private void l_logsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_logsMouseClicked
        l_accd.setBackground(exitcolor);
        l_accd.setForeground(exitforegroundcolor);
        l_changep.setBackground(exitcolor);
        l_changep.setForeground(exitforegroundcolor);
        l_recover.setBackground(exitcolor);
        l_recover.setForeground(exitforegroundcolor);
        l_logs.setBackground(hovercolor);
        l_logs.setForeground(foregroundcolor);
        
        DesktopPane.removeAll();
        ManageLogs mnl = new ManageLogs();
        DesktopPane.add(mnl).setVisible(true);  
    }//GEN-LAST:event_l_logsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel acc_uname;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel l_accd;
    private javax.swing.JLabel l_changep;
    private javax.swing.JLabel l_logs;
    private javax.swing.JLabel l_recover;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
