/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import User.UserPage;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class CheckOutPendings extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutPendings
     */
    public CheckOutPendings() {
        initComponents();
        displayCheckoutData();
        
        TableColumnModel UserColumnModel = c_table.getColumnModel();
       
        UserColumnModel.getColumn(0).setHeaderValue("ID");
        UserColumnModel.getColumn(1).setHeaderValue("ROOM ID");
        UserColumnModel.getColumn(2).setHeaderValue("FIRSTNAME");
        UserColumnModel.getColumn(3).setHeaderValue("LASTNAME");
        UserColumnModel.getColumn(4).setHeaderValue("CHECK-IN");
        UserColumnModel.getColumn(5).setHeaderValue("CHECK-OUT");
        UserColumnModel.getColumn(6).setHeaderValue("STATUS");

    c_table.getTableHeader().repaint();
    
    }
    
    public void displayCheckoutData() {
    try {
        dbConnector dbc = new dbConnector();
        String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        String sql = "SELECT b_id, rm_id, g_fname, g_lname, b_cin, b_cout, b_status " +
                     "FROM tbl_bookings " +
                     "WHERE b_status = 'Approved' AND b_cout <= '" + today + "'";

        ResultSet rs = dbc.getData(sql);
        c_table.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (SQLException ex) {
        System.out.println("Checkout Display Error: " + ex.getMessage());
    }
}
    
     Color hovercolor = new Color(255,255,255);
     Color exitcolor = new Color(0,0,153);
     Color foregroundcolor = new Color(0,0,0);
     Color exitforegroundcolor = new Color(255,255,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        b_button = new javax.swing.JLabel();
        cout_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(c_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 680, 280));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHECK-OUT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 680, 30));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CHECKOUT");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 230, 40);

        minimize1.setBackground(new java.awt.Color(0, 0, 153));
        minimize1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        minimize1.setForeground(new java.awt.Color(255, 255, 255));
        minimize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize1.setText("—");
        minimize1.setOpaque(true);
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize1MouseExited(evt);
            }
        });
        jPanel3.add(minimize1);
        minimize1.setBounds(810, 10, 40, 30);

        exit1.setBackground(new java.awt.Color(0, 0, 153));
        exit1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("X");
        exit1.setOpaque(true);
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        jPanel3.add(exit1);
        exit1.setBounds(850, 10, 40, 30);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        b_button.setBackground(new java.awt.Color(0, 0, 153));
        b_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_button.setForeground(new java.awt.Color(255, 255, 255));
        b_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_button.setText("Back");
        b_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_button.setOpaque(true);
        b_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_buttonMouseExited(evt);
            }
        });
        jPanel1.add(b_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 150, 40));

        cout_button.setBackground(new java.awt.Color(0, 0, 153));
        cout_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cout_button.setForeground(new java.awt.Color(255, 255, 255));
        cout_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cout_button.setText("Check-Out");
        cout_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cout_button.setOpaque(true);
        cout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cout_buttonMouseExited(evt);
            }
        });
        jPanel1.add(cout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimize1MouseClicked

    private void minimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseEntered
        minimize1.setBackground(new java.awt.Color(240,240,240));
        minimize1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_minimize1MouseEntered

    private void minimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseExited
        minimize1.setBackground(new java.awt.Color(0,0,153));
        minimize1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_minimize1MouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked

        dbConnector dbc = new dbConnector();
        Session sess = Session.getInstance();

        String action = "Logged Out from the System";
        dbc.insertData("INSERT INTO tbl_logs (usr_id, l_actions, l_date) VALUES ('"+sess.getUid()+"', '"+action+"', '"+LocalDateTime.now()+"' ) ");

        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
        exit1.setBackground(new java.awt.Color(240,240,240));
        exit1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
        exit1.setBackground(new java.awt.Color(0,0,153));
        exit1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exit1MouseExited

    private void b_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseClicked
        Session sess = Session.getInstance();
        String type = sess.getType();

        if (type.equals("Admin")) {
            AdminPage hmp = new AdminPage();
            hmp.setVisible(true);
        } else if (type.equals("User")) {
            UserPage usp = new UserPage();
            usp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
            return;
        }

        this.dispose();
    }//GEN-LAST:event_b_buttonMouseClicked

    private void b_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseEntered
        b_button.setBackground(hovercolor);
        b_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_b_buttonMouseEntered

    private void b_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buttonMouseExited
        b_button.setBackground(exitcolor);
        b_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_b_buttonMouseExited

    private void cout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cout_buttonMouseClicked
        int selectedRow = c_table.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a booking to check out.");
        return;
    }

    try {
        dbConnector dbc = new dbConnector();

        String bookingId = c_table.getValueAt(selectedRow, 0).toString();
        String roomId = c_table.getValueAt(selectedRow, 1).toString();

        String updateBooking = "UPDATE tbl_bookings SET b_status = 'Checked-Out' WHERE b_id = '" + bookingId + "'";
        dbc.updateData(updateBooking);

        String updateRoom = "UPDATE tbl_room SET r_status = 'Vacant' WHERE room_id = '" + roomId + "'";
        dbc.updateData(updateRoom);

        JOptionPane.showMessageDialog(this, "Guest checked out successfully!");
        
    displayCheckoutData();

    Session sess = Session.getInstance();
    String type = sess.getType();

    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    this.dispose();

    } catch (Exception ex) {
        System.out.println("Check-out Error: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Error during check-out. Please try again.");
    }
    }//GEN-LAST:event_cout_buttonMouseClicked

    private void cout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cout_buttonMouseEntered
        cout_button.setBackground(hovercolor);
        cout_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_cout_buttonMouseEntered

    private void cout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cout_buttonMouseExited
        cout_button.setBackground(exitcolor);
        cout_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_cout_buttonMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutPendings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutPendings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutPendings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutPendings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutPendings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_button;
    private javax.swing.JTable c_table;
    private javax.swing.JLabel cout_button;
    private javax.swing.JLabel exit1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minimize1;
    // End of variables declaration//GEN-END:variables
}
