/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Admin.HMPage;
import config.Session;
import config.dbConnector;
import hbsguiromo.LoginPage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class usersForm extends javax.swing.JFrame {

    /**
     * Creates new form usersForm
     */
    public usersForm() {
        initComponents();
        displayData();
        this.setResizable(false);
    }
    
        Color navcolor = new Color(102,255,51);
        Color hovercolor = new Color(0,255,51);
        Color exitcolor = new Color(51,51,51);
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_user");
            usersTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        acc_lname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p_back = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        p_add = new javax.swing.JPanel();
        add_label = new javax.swing.JLabel();
        p_refresh = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        p_update = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p_delete = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_lname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_lname.setForeground(new java.awt.Color(255, 255, 255));
        acc_lname.setText("LASTNAME");
        jPanel1.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USERS FORM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        p_back.setBackground(new java.awt.Color(51, 51, 51));
        p_back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_backMouseMoved(evt);
            }
        });
        p_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_backMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_backMouseExited(evt);
            }
        });
        p_back.setLayout(null);

        back.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backMouseMoved(evt);
            }
        });
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        p_back.add(back);
        back.setBounds(30, 10, 61, 26);

        jPanel1.add(p_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 50));

        usersTable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usersTable.setRowHeight(30);
        usersTable.setRowMargin(10);
        usersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(usersTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1070, 330));

        p_add.setBackground(new java.awt.Color(51, 51, 51));
        p_add.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_addMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_addMouseMoved(evt);
            }
        });
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        add_label.setBackground(new java.awt.Color(255, 255, 255));
        add_label.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        add_label.setForeground(new java.awt.Color(255, 255, 255));
        add_label.setText("ADD");
        add_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                add_labelMouseMoved(evt);
            }
        });
        add_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_labelMouseExited(evt);
            }
        });
        p_add.add(add_label);
        add_label.setBounds(80, 20, 45, 26);

        jPanel1.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 70));

        p_refresh.setBackground(new java.awt.Color(51, 51, 51));
        p_refresh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_refreshMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_refreshMouseMoved(evt);
            }
        });
        p_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_refreshMouseExited(evt);
            }
        });
        p_refresh.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REFRESH");
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        p_refresh.add(jLabel7);
        jLabel7.setBounds(80, 20, 110, 26);

        jPanel1.add(p_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 270, 70));

        p_update.setBackground(new java.awt.Color(51, 51, 51));
        p_update.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_updateMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_updateMouseMoved(evt);
            }
        });
        p_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_updateMouseExited(evt);
            }
        });
        p_update.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UPDATE");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        p_update.add(jLabel3);
        jLabel3.setBounds(100, 20, 90, 26);

        jPanel1.add(p_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 290, 70));

        p_delete.setBackground(new java.awt.Color(51, 51, 51));
        p_delete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_deleteMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_deleteMouseMoved(evt);
            }
        });
        p_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_deleteMouseExited(evt);
            }
        });
        p_delete.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DELETE");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        p_delete.add(jLabel5);
        jLabel5.setBounds(100, 20, 90, 26);

        jPanel1.add(p_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 280, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        HMPage hmp = new HMPage();
        hmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     Session sess = Session.getInstance();

    if(sess.getUid() == 0){
        JOptionPane.showMessageDialog(null, "No Shortcut Allowed you Muffin!, Login First! ;)");
        LoginPage mpg = new LoginPage();
        mpg.setVisible(true);
    this.dispose();
    }else{
        acc_lname.setText(""+sess.getFname());
    }


    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
       
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
        p_add.setBackground(exitcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void p_addMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseDragged
       
    }//GEN-LAST:event_p_addMouseDragged

    private void p_addMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseMoved
      p_add.setBackground(hovercolor);  
    }//GEN-LAST:event_p_addMouseMoved

    private void add_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_labelMouseClicked
     AddUserForm auf = new AddUserForm();
     auf.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_add_labelMouseClicked

    private void p_refreshMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_refreshMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_refreshMouseDragged

    private void p_refreshMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_refreshMouseMoved
        p_refresh.setBackground(hovercolor);
    }//GEN-LAST:event_p_refreshMouseMoved

    private void p_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_refreshMouseEntered
        
    }//GEN-LAST:event_p_refreshMouseEntered

    private void p_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_refreshMouseExited
        p_refresh.setBackground(exitcolor);
    }//GEN-LAST:event_p_refreshMouseExited

    private void p_updateMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updateMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_updateMouseDragged

    private void p_updateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updateMouseMoved
        p_update.setBackground(hovercolor); 
    }//GEN-LAST:event_p_updateMouseMoved

    private void p_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updateMouseEntered
        
    }//GEN-LAST:event_p_updateMouseEntered

    private void p_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updateMouseExited
        p_update.setBackground(exitcolor);
    }//GEN-LAST:event_p_updateMouseExited

    private void p_deleteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_deleteMouseDragged

    private void p_deleteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseMoved
        p_delete.setBackground(hovercolor); 
    }//GEN-LAST:event_p_deleteMouseMoved

    private void p_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseEntered
        
    }//GEN-LAST:event_p_deleteMouseEntered

    private void p_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseExited
        p_delete.setBackground(exitcolor);
    }//GEN-LAST:event_p_deleteMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       DeleteUserForm duf = new DeleteUserForm();
       duf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int rowIndex = usersTable.getSelectedRow();
        
        if(rowIndex < 0){
        JOptionPane.showMessageDialog(null,"Please Select an Item!");
        }else{
            
            
        try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = usersTable.getModel();
            ResultSet rs = dbc.getData("SELECT u_id, u_fname, u_lname, u_email, u_usern, u_type, u_status FROM tbl_user WHERE u_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
            if(rs.next()){
                
            UpdateUserForm uuf = new UpdateUserForm();
            
            uuf.user_id.setText(""+rs.getInt("u_id"));
            uuf.fn.setText(""+rs.getString("u_fname")); 
            uuf.ln.setText(""+rs.getString("u_lname"));
            uuf.em.setText(""+rs.getString("u_email"));
            uuf.cn.setText(""+rs.getLong("u_cnum"));
            uuf.un.setText(""+rs.getString("u_usern"));
            uuf.ps.setText(""+rs.getString("u_pass"));
            uuf.gd.setSelectedItem(""+rs.getString("u_gen"));
            uuf.ag.setText(""+rs.getString("u_age"));
            uuf.at.setSelectedItem(""+rs.getString("u_type"));
            uuf.st.setSelectedItem(""+rs.getString("u_status"));
            
            
            uuf.setVisible(true);
        this.dispose();
    }
       }catch(SQLException ex){
                System.out.println(""+ex);
            }
        
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        AddUserForm auf = new AddUserForm();
        auf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_addMouseClicked

    private void p_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updateMouseClicked
        int rowIndex = usersTable.getSelectedRow();
        
        if(rowIndex < 0){
        JOptionPane.showMessageDialog(null,"Please Select an Item!");
        }else{
            
            
        try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = usersTable.getModel();
            ResultSet rs = dbc.getData("SELECT u_id, u_fname, u_lname, u_email, u_usern, u_type, u_status FROM tbl_user WHERE u_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
            if(rs.next()){
                
            UpdateUserForm uuf = new UpdateUserForm();
            
            uuf.user_id.setText(""+rs.getInt("u_id"));
            uuf.fn.setText(""+rs.getString("u_fname")); 
            uuf.ln.setText(""+rs.getString("u_lname"));
            uuf.em.setText(""+rs.getString("u_email"));
            uuf.cn.setText(""+rs.getLong("u_cnum"));
            uuf.un.setText(""+rs.getString("u_usern"));
            uuf.ps.setText(""+rs.getString("u_pass"));
            uuf.gd.setSelectedItem(""+rs.getString("u_gen"));
            uuf.ag.setText(""+rs.getString("u_age"));
            uuf.at.setSelectedItem(""+rs.getString("u_type"));
            uuf.st.setSelectedItem(""+rs.getString("u_status"));
            
            
            uuf.setVisible(true);
        this.dispose();
    }
       }catch(SQLException ex){
                System.out.println(""+ex);
            }
        
        }
    }//GEN-LAST:event_p_updateMouseClicked

    private void add_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_labelMouseEntered

    }//GEN-LAST:event_add_labelMouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        p_update.setBackground(exitcolor); 
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        p_update.setBackground(hovercolor); 
    }//GEN-LAST:event_jLabel3MouseMoved

    private void add_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_labelMouseExited
        p_add.setBackground(exitcolor); 
    }//GEN-LAST:event_add_labelMouseExited

    private void add_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_labelMouseMoved
        p_add.setBackground(hovercolor); 
    }//GEN-LAST:event_add_labelMouseMoved

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        p_delete.setBackground(exitcolor); 
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        p_delete.setBackground(hovercolor); 
    }//GEN-LAST:event_jLabel5MouseMoved

    private void p_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseClicked
        DeleteUserForm duf = new DeleteUserForm();
        duf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_deleteMouseClicked

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        p_refresh.setBackground(hovercolor);
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        p_refresh.setBackground(exitcolor);
    }//GEN-LAST:event_jLabel7MouseExited

    private void p_backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_backMouseMoved
        p_back.setBackground(hovercolor);
    }//GEN-LAST:event_p_backMouseMoved

    private void p_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_backMouseExited
        p_back.setBackground(exitcolor);
    }//GEN-LAST:event_p_backMouseExited

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        p_back.setBackground(exitcolor);
    }//GEN-LAST:event_backMouseExited

    private void p_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_backMouseClicked
        HMPage hmp = new HMPage();
        hmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_backMouseClicked

    private void backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseMoved
       p_back.setBackground(hovercolor);
    }//GEN-LAST:event_backMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel add_label;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel p_back;
    private javax.swing.JPanel p_delete;
    private javax.swing.JPanel p_refresh;
    private javax.swing.JPanel p_update;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
