/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UsersInternal;

import Admin.AdminPage;
import User.UserPage;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.Window;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mark Kevin Romo
 */
public class DeleteUserForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteUserForm
     */
    
    String destination = "";
    File selectedFile;
    String path = "";
    String oldpath = "";
    
     Color hovercolor = new Color(255,255,255);
     Color exitcolor = new Color(0,0,153);
     Color foregroundcolor = new Color(0,0,0);
     Color exitforegroundcolor = new Color(255,255,255);
    
    public DeleteUserForm() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    
    displayData();
    
    Border line = BorderFactory.createLineBorder(Color.BLACK);
    Border margin = BorderFactory.createEmptyBorder(5, 10, 5, 10); 
    Border compound = BorderFactory.createCompoundBorder(line, margin);
    
    user_id.setBorder(compound);
    fn.setBorder(compound);
    ln.setBorder(compound);
    em.setBorder(compound);
    gd.setBorder(compound);
    cn.setBorder(compound);
    un.setBorder(compound);
    ag.setBorder(compound);
    at.setBorder(compound);
    
    TableColumnModel columnModel = usersTable.getColumnModel();
       
        columnModel.getColumn(0).setHeaderValue("ID");
        columnModel.getColumn(1).setHeaderValue("FIRSTNAME");
        columnModel.getColumn(2).setHeaderValue("USERNAME");

    usersTable.getTableHeader().repaint();
    
    usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = usersTable.getSelectedRow();
        String tableClick = (usersTable.getModel().getValueAt(row, 0).toString());

        try {
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '" + tableClick + "'");
            if (rs.next()) {
                
                AddUserForm auf = new AddUserForm();
                user_id.setText(rs.getString("u_id"));
                fn.setText(rs.getString("u_fname"));
                ln.setText(rs.getString("u_lname"));
                em.setText(rs.getString("u_email"));
                cn.setText(rs.getString("u_cnum"));
                un.setText(rs.getString("u_usern"));
                gd.setSelectedItem(rs.getString("u_gen"));
                ag.setText(rs.getString("u_age"));
                at.setSelectedItem(rs.getString("u_type"));
                image.setIcon(auf.ResizeImage(rs.getString("u_image"),null, image));
                oldpath = rs.getString("u_image");
                path = rs.getString("u_image");
                destination = rs.getString("u_image");
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error retrieving data: " + ex.getMessage());
        }
    }
});
    }
    
    public void deleteImage(String imagePath) {
    File imageFile = new File(imagePath);
    if (imageFile.exists()) {
        if (imageFile.delete()) {
            System.out.println("Image deleted successfully.");
        } else {
            System.out.println("Failed to delete the image.");
        }
    } else {
        System.out.println("Image file does not exist.");
    }
}

    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT u_id, u_fname, u_usern FROM tbl_user");
            usersTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gd = new javax.swing.JComboBox<>();
        em = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        at = new javax.swing.JComboBox<>();
        ag = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        user_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        d_button = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("User ID:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Firstname:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Lastname:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gender:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        gd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gd.setEnabled(false);
        gd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdActionPerformed(evt);
            }
        });
        jPanel3.add(gd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, 30));

        em.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        em.setEnabled(false);
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emKeyTyped(evt);
            }
        });
        jPanel3.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 30));

        ln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ln.setEnabled(false);
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnKeyTyped(evt);
            }
        });
        jPanel3.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 30));

        fn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fn.setEnabled(false);
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnKeyTyped(evt);
            }
        });
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("C Number:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Username:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Age:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Acc Type:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 70, 30));

        at.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        at.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        at.setEnabled(false);
        jPanel3.add(at, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 30));

        ag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ag.setEnabled(false);
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        ag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agKeyTyped(evt);
            }
        });
        jPanel3.add(ag, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 170, 30));

        un.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        un.setEnabled(false);
        jPanel3.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 170, 30));

        cn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cn.setEnabled(false);
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnKeyTyped(evt);
            }
        });
        jPanel3.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, 30));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(usersTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 260, 130));

        user_id.setEnabled(false);
        jPanel3.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jPanel1.add(image);
        image.setBounds(10, 10, 240, 160);

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 260, 180));

        d_button.setBackground(new java.awt.Color(0, 0, 153));
        d_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d_button.setForeground(new java.awt.Color(255, 255, 255));
        d_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d_button.setText("Delete");
        d_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        d_button.setOpaque(true);
        d_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d_buttonMouseExited(evt);
            }
        });
        jPanel3.add(d_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 150, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdActionPerformed

    private void emKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emKeyTyped

    private void lnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_lnKeyTyped

    private void fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_fnKeyTyped

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void agKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();

        }
    }//GEN-LAST:event_agKeyTyped

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnActionPerformed

    private void cnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();

        }
    }//GEN-LAST:event_cnKeyTyped

    private void d_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d_buttonMouseClicked
    dbConnector dbc = new dbConnector();

if (fn.getText().isEmpty() || ln.getText().isEmpty() || em.getText().isEmpty() ||
    cn.getText().isEmpty() || un.getText().isEmpty() || ag.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Choose a user to delete in the table");
    return;
}

String email = em.getText();
String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
if (!email.matches(emailRegex)) {
    JOptionPane.showMessageDialog(null, "Please enter a valid email address.");
    return;
}

String userId = user_id.getText();
String imagePath = "";
try {
    ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '" + userId + "'");
    if (!rs.next()) {
        JOptionPane.showMessageDialog(null, "User not found. Please select a valid user.");
        return;
    }

    imagePath = rs.getString("u_image");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error checking user existence: " + ex.getMessage());
    return;
}

int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
if (confirmation == JOptionPane.YES_OPTION) {
    String query = "DELETE FROM tbl_user WHERE u_id = '" + userId + "'";

    if (dbc.updateData(query)) {
        if (imagePath != null && !imagePath.isEmpty()) {
            deleteImage(imagePath);
        }
        
    Session sess = Session.getInstance();
        String action = "Deleted User Record with ID of " + userId;
        dbc.insertData("INSERT INTO tbl_logs (usr_id, l_actions, l_date) VALUES ('"
    + sess.getUid() + "', '" + action + "', '" + java.time.LocalDateTime.now() + "')");

        JOptionPane.showMessageDialog(null, "User deleted successfully!");
        
    String type = sess.getType();

    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
        
    } else {
        JOptionPane.showMessageDialog(null, "Deleting User Failed. Please try again.");
    }
}
    }//GEN-LAST:event_d_buttonMouseClicked

    private void d_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d_buttonMouseEntered
        d_button.setBackground(hovercolor);
        d_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_d_buttonMouseEntered

    private void d_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d_buttonMouseExited
        d_button.setBackground(exitcolor);
        d_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_d_buttonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ag;
    public javax.swing.JComboBox<String> at;
    public javax.swing.JTextField cn;
    public javax.swing.JLabel d_button;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    public javax.swing.JComboBox<String> gd;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField ln;
    public javax.swing.JTextField un;
    private javax.swing.JTextField user_id;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
