/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;

import Admin.AdminPage;
import MainPage.LoginPage;
import User.UserPage;
import config.HashPass;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Mark Kevin Romo
 */
public class ChangePass extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePass
     */
    public ChangePass() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    Border line = BorderFactory.createLineBorder(Color.BLACK);
    Border margin = BorderFactory.createEmptyBorder(5, 10, 5, 10); 
    Border compound = BorderFactory.createCompoundBorder(line, margin);

    u_id.setBorder(compound);
    u_opass.setBorder(compound);
    u_npass.setBorder(compound);
    u_cpass.setBorder(compound);
    }
    
     Color hovercolor = new Color(255,255,255);
     Color exitcolor = new Color(0,0,153);
     Color foregroundcolor = new Color(0,0,0);
     Color exitforegroundcolor = new Color(255,255,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        u_opass = new javax.swing.JTextField();
        u_npass = new javax.swing.JTextField();
        u_cpass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 110, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Old Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 150, 87, 17);

        u_id.setEnabled(false);
        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });
        jPanel1.add(u_id);
        u_id.setBounds(360, 100, 210, 30);

        u_opass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_opassActionPerformed(evt);
            }
        });
        jPanel1.add(u_opass);
        u_opass.setBounds(360, 140, 210, 30);
        jPanel1.add(u_npass);
        u_npass.setBounds(360, 180, 210, 30);
        jPanel1.add(u_cpass);
        u_cpass.setBounds(360, 220, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("New Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 190, 93, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 230, 115, 17);

        save_button.setBackground(new java.awt.Color(0, 0, 153));
        save_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("Save");
        save_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_buttonMouseExited(evt);
            }
        });
        jPanel1.add(save_button);
        save_button.setBounds(390, 270, 140, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Session sess = Session.getInstance();
      
      if(sess.getUid() == 0){
      JOptionPane.showMessageDialog(null, "No Shortcut Allowed!, Login First!");
        LoginPage mpg = new LoginPage();
        mpg.setVisible(true);
        this.dispose();
      }else{
      u_id.setText(""+sess.getUid());
      }
    }//GEN-LAST:event_formInternalFrameActivated

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void u_opassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_opassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_opassActionPerformed

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked
        dbConnector dbc = new dbConnector();
    Session sess = Session.getInstance();
    try {
        String pass, oldpass, hashpass;
        hashpass = sess.getPassword(); 
        
        String newPass = u_npass.getText();
        String confirmPass = u_cpass.getText();
        String oldPassword = u_opass.getText();
        
        
        if (newPass.isEmpty() || confirmPass.isEmpty() || oldPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
            return; 
        }
        
        oldpass = HashPass.hashPassword(oldPassword);
        if (!(hashpass.equals(oldpass))) {
            JOptionPane.showMessageDialog(null, "Wrong old password!");
            return; 
        }
        
        if (!(newPass.equals(confirmPass))) {
            JOptionPane.showMessageDialog(null, "New passwords do not match!");
            return; 
        }
        
        pass = HashPass.hashPassword(newPass);
        dbc.insertData("UPDATE tbl_user SET u_pass ='" + pass + "' WHERE u_id ='" + u_id.getText() + "'");
        JOptionPane.showMessageDialog(null, "Password updated successfully!");
        
    String type = sess.getType();
    if (type.equals("Admin")) {
        AdminPage hmp = new AdminPage();
        hmp.setVisible(true);
    } else if (type.equals("User")) {
        UserPage usp = new UserPage();
        usp.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Unknown account type: " + type);
        return;
    }

    this.dispose();

    } catch (NoSuchAlgorithmException ex) {
        System.out.println("Error: " + ex);
    }
    }//GEN-LAST:event_save_buttonMouseClicked

    private void save_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseEntered
        save_button.setBackground(hovercolor);
        save_button.setForeground(foregroundcolor);
    }//GEN-LAST:event_save_buttonMouseEntered

    private void save_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseExited
        save_button.setBackground(exitcolor);
        save_button.setForeground(exitforegroundcolor);
    }//GEN-LAST:event_save_buttonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel save_button;
    private javax.swing.JTextField u_cpass;
    private javax.swing.JTextField u_id;
    private javax.swing.JTextField u_npass;
    private javax.swing.JTextField u_opass;
    // End of variables declaration//GEN-END:variables
}
